### ISSUE TITLE
Add the ability to create a calendar record

### ISSUE THREAD

**Issue by jcbernard83** [pakerwreah/Calendr#111]
Hi,

Could you add the ability to create an calendar record ?

Like the ItSyCal app.

Thanks.

**Comment by pakerwreah** [comment]
Hello 👋🏻 
I have no plans of implementing this feature, mostly because it will never have all the bells and whistles that the native Calendar app has, but also because it was never the purpose of this app.
I prefer to keep it read-only, so I don't screw up my work meetings because of some weird bug.

On iOS that is very easy to do, because Apple provides a native EKEventViewController to be able to create and edit events, but sadly on macOS I would have to create everything from scratch.
