### ISSUE TITLE
Alternative day view

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#12]
It would be great if you could add an option to have alternative day view like this one on the screenshot I simulated
![Sin título 2](https://user-images.githubusercontent.com/823394/108505047-80ca6580-72bf-11eb-93d9-61ddce3c1542.jpg)

**Comment by pakerwreah** [comment]
This is very good, but that change would make the app too work-focused and it would go against the app main goal which is to give you a glimpse of your day in the smallest widget possible, otherwise I would just have made it a window with all the whistles that the native Calendar.app has.

Also, not everyone has the same work hours, so this would have to be configurable and you'll need to scroll to see other events that fall outside of that time window.

What I agree on is that would be nice to know how much time we have before the next event.
The way I can think of to make this work is just having something like:

<sub>1 hour, 30 min</sub>

| Event 1 
| <sub>14:00 - 14:30</sub>

<sub>45 min</sub>

| Event 2
| <sub>15:15 - 16:00</sub>

**Comment by gferreroferri** [comment]
Something you could do is to make event blocks bigger or smaller depending on the duration. It will at least help to understand visually how long the event will take. The time between events like you mentioned above would also be a good idea

**Comment by pakerwreah** [comment]
Closed in favor of #21
