### ISSUE TITLE
Show birthdays under Next Event

### ISSUE THREAD

**Issue by belazaras** [pakerwreah/Calendr#124]
Showing the birthdays in the menu bar would be cool, otherwise sometimes I think there's no event but that's happening and I wanna say hi.

**Comment by pakerwreah** [comment]
The app does not show all-day events in the menu bar, because you can have more than 1 and it would be messy.
Perhaps I could change the app icon to a 🎁 like we have in the event list, so it won't compete with upcoming events. 
It also solves the issue with having more than 1 birthday, because you will have to open the calendar anyway to see who it is.

**Comment by pakerwreah** [comment]
I will explore some ideas and see what fits better without adding too much complexity.

**Comment by belazaras** [comment]
yes, that makes sense, the icon sounds efficient and clear.
