### ISSUE TITLE
Possibility to add new events

### ISSUE THREAD

**Issue by lKingID** [pakerwreah/Calendr#143]
Hey,

first of all "Слава Україні".  Thank you for that amazing app. I'd like to know if it is possible to add Events in the App. Sadly, i haven't seen or found that function.

**Comment by pakerwreah** [comment]
Hi 👋🏻 I'm glad you liked!

This is just a personal project to organize my own life and it was never the intention to create or modify events, just to view them in a more convenient way.
I don't want to accidentally delete all of my events because of a dumb code mistake :)

On iOS, Apple provides an out-of-the-box view controller to do that, but unfortunately it's not available on macOS.
I've tried very hacky ways to run this controller separately using Catalyst, but it ended up not working very well.
If one day Apple decides to provide this feature on macOS I will be more than happy to add it to the app.

As for now, I don't have time or motivation to create one from scratch because that would generate a lot of maintenance.

I hope you understand and continue to support the app 😇

**Comment by lKingID** [comment]
Hi @pakerwreah Thanks for your reply.

Sadly, that this is not possible right now. I wonder how other App's like Calender366 are doing it on Mac.

**Comment by pakerwreah** [comment]
As I said earlier: to create that feature from scratch would generate a lot of maintenance.
Modifying events is way more critical that just reading them. That requires a lot of attention and testing.

Calender366 makes a lot of money from their app, so they surely have a team to work on it full time.
