### ISSUE TITLE
Several small feature requests / quality of life improvements

### ISSUE THREAD

**Issue by Shagon94** [pakerwreah/Calendr#155]
Hello there 👋 after using [MeetingBar](https://github.com/leits/MeetingBar) and suffering the battery drain on M1 laptop I had some notes on some features that you might find useful.

- Hide Calendar 
- Week starts on (monday/sunday)
- Days to show on calendar (monday-friday, or the current monday-sunday)
- Integrate both "next event" and the menu bar itself in one, for example - instead of date I found it really useful to know the next event

Overall I really like the design :)

**Comment by pakerwreah** [comment]
Hello 👋🏻 
I will try to make sense of what you wrote, because it's not very detailed, but here we go.

- `Hide Calendar`
You can hide the icon in the app settings.

- `Week starts on (monday/sunday)`
The app respects your macOS configuration, so you can change that in:
Settings > Language & Region > First day of week

- `Days to show on calendar (monday-friday, or the current monday-sunday)`
That's a very specific request and I don't think it would be very useful for most users.

- `Integrate both "next event" and the menu bar itself in one...`
That's separated by design. You can have both next event and next reminder displayed at the same time and, if you have a macbook with a notch and there's not enough space, macOS will hide items from left to right.

- `...instead of date I found it really useful to know the next event`
You can hide the date in the app settings.

**Comment by Shagon94** [comment]
For "hide calendar" I was referring to the calendar when you click on the actual calendar icon, not the icon itself. Meaning in the context menu the calendar that is displayed.

> Integrate both "next event" and the menu bar itself in one...

Not sure why I understand the reasoning, can you expand on the explanation? Having an option to only have one seems like a logical thing considering we don't want to clutter the menu bar. I installed [Dozer](https://github.com/Mortennn/Dozer) just to hide unnecessary things running in the background.

**Comment by pakerwreah** [comment]
1. The whole point of this app is to be a calendar. Perhaps what you really want is something like MeetingBar, as you mentioned earlier.

2. If you have icon + date + event + reminder, that would be a very big menu bar item and macOS will hide it if it doesn't fit entirely in the menu bar.
People might also want to place those 3 informations in different places, so having them separate allows you to have flexibility to configure it the way it fits best.
