### ISSUE TITLE
Request to Enhance macOS Multi-Monitor Experience with Calendar Widget

### ISSUE THREAD

**Issue by nicho810** [pakerwreah/Calendr#186]
Hi Carlos,

I hope this message finds you well. First and foremost, I wanted to express my sincere appreciation for the outstanding software you have developed for macOS. It has greatly enhanced my productivity and made my daily tasks much more efficient. Thank you for your hard work and dedication.

However, while using the application in a multi-monitor setup on macOS, I have come across a potential area for improvement. I would like to suggest the addition of a calendar widget on the top bar of each screen, particularly when multiple displays are in use. Currently, the absence of this widget on inactive screens' top bars creates a minor inconvenience and leaves the bar space unutilized.

I believe that implementing this enhancement would further elevate the functionality and user experience of your software. It would provide users with quick and easy access to their calendar on every screen, regardless of its activation status. 

Thank you for taking the time to consider this improvement. Your efforts in addressing this issue would be highly appreciated.

BR,
Nicho

**Comment by pakerwreah** [comment]
Hi Nicho, That's a known issue.

I'm attaching the view outside of the native menu bar button to save space around it and to have left+right click actions working properly. That causes the view to disappear on inactive screens.

Even if I make it not disappear, its length will be based on whether you are focusing the macbook screen (with the notch) or an external display and macOS considers both menu bars as being the same, so I cannot have different widget styles on each screen at the same time.

To be honest, I don't have plans to fix this.
I personally don't think it makes sense to look at the inactive screen, with barely readable widgets, instead of looking to the active screen. As you said, it's a minor inconvenience and fixing it will cause other issues. (I've tried multiple times)
