### ISSUE TITLE
Calendr for macOS 15

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#198]
@pakerwreah,

I’d like to take this opportunity to thank you for maintaining the application.

I wanted to ask if you could give us a preview of any changes or updates the app may receive in light of the (finally) integration of reminders with the calendar for the upcoming macOS 15 update, which you have probably seen.

Here are a few things on my wishlist:
- A design more similar to macOS (maybe similar to [this](https://ibb.co/p3gZXd4))
- A larger window when clicking on the calendar view
- The possibility to toggle reminders from the window or directly in the menu bar

Thanks a lot!

**Comment by pakerwreah** [comment]
Thanks! 🙇🏻‍♂️ 

I will install the update as soon as it gets released.

- The events + reminders integration seems to be mostly at a UI level on the new macOS. We already have similar APIs to fetch both, and Calendr already supports them seamlessly, so I see no improvements there at a first glance.

- A larger window or the new full-featured design you mentioned are far from the purpose of Calendr, which is to be a simple tiny calendar on your menu bar.

- `The possibility to toggle reminders from the window or directly in the menu bar`
You can already do that inside the details window or by right-clicking the reminder in the menu bar.

I try not to implement too many features just because they are possible, but rather if they make sense to my daily workflow. If I find any cool new features that makes sense to me, I will probably explore it.

**Comment by ilMagnifico** [comment]
> * `The possibility to toggle reminders from the window or directly in the menu bar`
>   You can already do that inside the details window or by right-clicking the reminder in the menu bar.

Oh, I didn't know that.😮
What do you think about having an interface for reminders similar to that of the Reminders app, with a small circle that can be selected to mark the reminder as completed?

**Comment by pakerwreah** [comment]
I thought about it a few times actually, but adding that circle in the menu bar would mean occupying more space, and space is a luxury we don't have, specially after the notch was invented. 🤦🏻‍♂️ 

Another point is that, since the UI is very small, you could accidentally tap the circle, then you would have to open the Reminders app to recover it, which would be annoying.

That's why I made things right-clickable. It's also very scalable, I can add more actions to the context menu if I want to.
<sub>By the way, you can also double-click the date cells in the calendar, if you didn't know. I should probably create a documentation for these hidden features. 😅</sub>

Some people would like that feature, some would not, and then I would have to create a new switch to opt-in/out, and I would have 2 branches of code to maintain that do the exactly same thing.

**Comment by ilMagnifico** [comment]
> By the way, you can also double-click the date cells in the calendar, if you didn't know. I should probably create a documentation for these hidden features. 😅

I thought so. I agree about creating some form of small documentation, like when you open an updated app for the first time, with a brief overview of the new features.
