### ISSUE TITLE
Enable opening the calendar in week view when clicking on a week number

### ISSUE THREAD

**Issue by laurentNoudohounsi** [pakerwreah/Calendr#261]
Hello,

I've a proposal regarding the calendar opening view.

**Current behavior**

The calendar opens in:
- month view when we click on the calendar icon
- day view when we double click on a day

**Proposed Feature**

Would it be a good idea to allow users to open the calendar in week view when they click on a week number?

**Implementation Considerations**

From my observations, the following steps might be needed to implement this:

1) Add a case for `week` in the enum located here: [CalendarScript.swift](https://github.com/pakerwreah/Calendr/blob/0fb5b5de49ed3f63012408864b2dcaa25505bfa3/Calendr/Automation/CalendarScript.swift#L19C1-L22C6) .

2) use the method `calendarScript.openCalendar(at: date, mode: .week)` in the `WeekNumberCellView.swift`.

Alternatively, it might be worth considering making changes in `MainViewController.swift` and `CalendarViewModel.swift` to better handle this functionality.

**Alternative Proposal**
Another possible implementation could be to add an option in the preferences that allows users to choose whether the month view or the week view is opened when they click on the calendar icon.

I’m suggesting this feature because I personally find the week view more useful for most cases. It’s possible that other users might feel the same way.

**Comment by Ariandr** [comment]
I agree that opening the week view would be really convenient, since the month view isn't that useful for me personally.
But since I don't have week numbers shown, as an additional point to trigger the opening of the week view in the system Calendar I would use these area/labels, since they show the weekly range. It can be a double click too.

![image](https://github.com/user-attachments/assets/83d829d2-8b6c-498c-bd62-50fb754c96c3)

**Comment by pakerwreah** [comment]
I think that clicking the week names is a very obscure way of triggering it. That's related to the day, not the week.

I don't have week numbers always visible either, I use the shortcut to toggle it on and off when I need it.

I personally prefer the month view, so I believe having a configuration for the calendar button would please everyone.

I'm also assuming we want to open the week from the selected date, because that's the behavior of the month view, it opens in the selected month. That also covers the case where you would click a specific week number.

The default behavior would be opening in the current week, since by default the current date is selected, unless you have "Preserve selected date on hide" enabled, but you can just reset to the current date manually, I'm not gonna create a bunch of exceptions for this feature.

**Comment by laurentNoudohounsi** [comment]
> I think that clicking the week names is a very obscure way of triggering it. That's related to the day, not the week.

@Ariandr I think the same as @pakerwreah. It would be not intuitive to click on a these label to open a week view.

Also, thank you to both of you for pointing that the week numbers isn't always open. I opened it since the beginning so it was natural for me 😅



> I personally prefer the month view, so I believe having a configuration for the calendar button would please everyone.

Totally agree! And it will be the most intuitive / easy to implement (without thinking about a lot of uses cases) too.




> I'm also assuming we want to open the week from the selected date, because that's the behavior of the month view, it opens in the selected month. That also covers the case where you would click a specific week number.

Tbh, that was my first thought but seeing that double clicking on a day opened the day view I didn't push for that since it makes sense too.
