### ISSUE TITLE
Auto-update fails when Calendr kept at ~/Applications

### ISSUE THREAD

**Issue by PuzzledUser** [pakerwreah/Calendr#264]
I keep all third party apps in an Applications folder in my Home folder. This seems to traumatise your update script (irrespective of what I say to your grant permissions prompt — change nothing and select /Applications, or change to ~/Applications).

EDIT: I was on v1.13.3. Mac OS 14.6.1

**Comment by pakerwreah** [comment]
The update code will abort if you change the path, because it won't have permission to delete the old app.

No matter what you do, it will try to delete from `/Applications` and will fail because your app is on `~/Applications`.

Previously I was just getting the location of your currently running app, but if you move it around, sometimes macOS gatekeeper will put it into quarantine and give me a random path like `/Volumes/random-number/Calendr.app`, which breaks the entire update process.

I will try to improve this in two ways:
1. Only fallback to `/Applications` if the system gives me a "corrupted" path. This will open the save panel in the correct place for you, if nothing goes wrong.
2. Always try to use the path that you selected. That way if the system messes up you can always select the correct location.

**Comment by PuzzledUser** [comment]
Thanks. I guess release for [1.14.1](https://github.com/pakerwreah/Calendr/milestone/62) will appear in due course (automatically 😉)...

**Comment by pakerwreah** [comment]
Yeah, but it will still use the old updater, so you will have to do this one manually.

**Comment by PuzzledUser** [comment]
Tested. Works perfectly for me.

**Comment by pakerwreah** [comment]
I think I broke this 🥲
I just got an error report from someone using 1.19.4, which I'm pretty sure it's you 😆
<sub>(because this version was never released)</sub>

**Comment by pakerwreah** [comment]
Well, turns out it sometimes gets stuck with a security flag that makes it impossible for me to know where your app is.
It reports the path as `/private/var/folders/.../T/AppTranslocation/[UUID]/d/Calendr.app` and I don't have access to delete the "old" file.
When that happens, I just fallback to the default `/Applications` folder, but since the old file doesn't exist there, the update fails.

What helps is to unzip the file in a different folder and then moving it to `~/Applications`.
That process removes the quarantine flag from the app. ¯\\\_(ツ)_/¯

If I use something like BetterZip and try to extract the app directly to `~/Applications`, it keeps the quarantine flag.

**Comment by PuzzledUser** [comment]
Yeah Twas me. I didn’t have the urge to explore and just sighed and manually got round the issue 😉

<img width="378" height="314" alt="Image" src="https://github.com/user-attachments/assets/21e7b5d4-2fbd-4c45-9a9e-059b9f40a8b3" />
