### ISSUE TITLE
Add "Search" function on the menu

### ISSUE THREAD

**Issue by ilMagnifico** [pakerwreah/Calendr#268]
<img width="330" alt="Screenshot 2024-10-20 alle 11 17 23" src="https://github.com/user-attachments/assets/116b007b-2f77-456f-9685-08d9567c899b">

Since there is space, we may add the search function (with a search icon) instead of having to click on the last button and then click "Search". I know there is the keyboard shortcuts, but since we have free space why not adding it anyway?

Spoiler: @pakerwreah yes for today I finished my work as feedbacker 😅

**Comment by pakerwreah** [comment]
Spaces are nice for separation of concerns. I don't want the ui to become cluttered with components in every single pixel.

I personally don't even use the search function that much. It would be annoying to have it always visible.

It also interferes with the keyboard in general.

So that's a "no" from me 😉
