### ISSUE TITLE
Suggestion for all day events

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#28]
Great new update, congrats!

One suggestion for the all day events: Instead of having a section for all day events and another one, using space, maybe it they could be shown as in the apple calendar app month cells, with coloured background so they are easy to pinpoint without needing a text separation

**Comment by pakerwreah** [comment]
The background color draws too much attention; since I'm doing that for in-progress events, it can be easily mistaken.

I'll make some experiments when I have ~~some ideas~~ free time. 

I'm working hard to get this close to feature complete so people can use it without major changes every two weeks 😅
