### ISSUE TITLE
[Feature Request] Ability to delete events

### ISSUE THREAD

**Issue by winkelmayer** [pakerwreah/Calendr#305]
Currently, it is possible to view events, but not **edit or delete them directly from Calendr**. Would it be possible to add the ability to do that?

**Comment by pakerwreah** [comment]
Sorry, this is too risky. I don't want to delete anyone's events by accident.

Creating and editing generates a lot of maintenance and will never be feature complete. It will only be implemented if Apple provides the native view controller to do that, as they do for iOS, otherwise it's out of scope.

**Comment by ilMagnifico** [comment]
I agree strong edit/deletion of reminders/events should be done on the native app.
