### ISSUE TITLE
Bug with personalised date

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#37]
I have changed my date format on the System settings but it does not show properly in the event details. See screenshot

<img width="330" alt="Captura de pantalla 2021-03-28 a las 20 36 56" src="https://user-images.githubusercontent.com/823394/112761740-6b0a3780-9005-11eb-8c67-4e8d9d1791d7.png">

These are my settings
<img width="618" alt="Captura de pantalla 2021-03-28 a las 20 38 54" src="https://user-images.githubusercontent.com/823394/112761819-b290c380-9005-11eb-8fa0-99e7efae32eb.png">

**Comment by pakerwreah** [comment]
These configurations don't affect date intervals

**Comment by gferreroferri** [comment]
why it shows then this strange semana del mes: 5 ?

**Comment by pakerwreah** [comment]
@gferreroferri can you verify if this fixes it?
[Calendr.app.zip](https://github.com/pakerwreah/Calendr/files/6217940/Calendr.app.zip)

**Comment by gferreroferri** [comment]
Actually this new version makes the 's' disappear from the expected date that should be s13 based on the local config
<img width="289" alt="Captura de pantalla 2021-03-29 a las 15 29 45" src="https://user-images.githubusercontent.com/823394/112836736-a2c7bc80-90a3-11eb-871e-62f4dfdb7f96.png">

**Comment by pakerwreah** [comment]
Well, that's the real problem.

The `DateIntervalFormatter` uses your config as a "hint" to build the final string with the elements you want, but since it can modify everything and hide elements not needed (if the start & end is on the same day), it discards everything else that you might put in between the date elements.
That's why it uses that weird description like `├week of month: 2┤` or `(quarter: 1)`, because since it cannot use yours, the number alone would make no sense.

To solve this I will have to stop using this formatter and write:
```
from: <date+time>
to: <date+time>
```
so I can use your full config template with each date alone.

That will make the date section very ugly, since it will repeat everything but I can try to compose it from scratch when it's the same day (the most frequent case) and clean it up a little bit.

**Comment by gferreroferri** [comment]
I think then it is good as it was in the 1.1.1 version
