### ISSUE TITLE
Reminders: Overdue should be carried to today

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#40]
For the new reminder implementation: overdue reminders should be carried on to today until they are completed, in my opinion

**Comment by pakerwreah** [comment]
I understand, but unfortunately, that changes too much the calendar's behavior 😕 

If previous day events would have an impact on the current day behavior, we could potentially have some bugs between months, since for performance reasons, I only fetch the current viewport data (42 days).

As it is today, the reminders implementation shares 90% of the events logic. To do what you're asking I would have to create a totally new implementation for it. That's not an easy task to do, specially for a "nice to have, but not essential" feature like reminders.

**Comment by gferreroferri** [comment]
Ok. Understood. Thanks
