### ISSUE TITLE
Data Collection and General Safeness

### ISSUE THREAD

**Issue by JuNkY14257** [pakerwreah/Calendr#68]
Hi, are you planning on signing/submitting the app so Apple can confirm it has no malware? Also, is this app safe to use? Does it collect data (considering how it pulls calendar events and reminders from iCloud)? And lastly, why does the app have no icon?

**Comment by pakerwreah** [comment]
This is just a personal project to organize my own schedule. I have no plans on submitting it to the store or monetizing it.

All you see in the app is pure visualization of local data, accessed using native macOS APIs and no data is sent anywhere.

The [MIT License](https://github.com/pakerwreah/Calendr/blob/master/LICENSE) says: `the software is provided "as is", without warranty of any kind`, but if you trust my word I would say it is safe to use ¯\\\_(ツ)\_/¯

The code is totally open-source, so you can see it for yourself.

The app has no icon because I'm not a designer and, since it's not even shown in the Dock, it's not that important.
