### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by decodism** [pakerwreah/Calendr#69]
Hello, good job on this app, especially the clean visual. Here are some suggestions:
- Use a circle for the reset icon. The circled arrow looks more like a "refresh". Also, the system date picker uses a dot.
- Use a pin when the popup is not pinned and a slashed pin when it is. The lock looks more like a "lock on edits".
- Provide the same date formatting options as the system clock in the menu bar. That is:
```swift
["E", "MMMd", "EMMMd"].map() { DateFormatter.dateFormat(fromTemplate: $0, options: .zero, locale: .current)! }
```
- Provide an option to force the use of a capital letter for the date in the menu bar.
- In the settings, the last item is cut at the bottom.
- Provide an option not to reset the calendar when the popup is reopened.
- Hovering over a date with the option key could display the list of events for that date.

**Comment by pakerwreah** [comment]
- The icons look fine to me, that's a matter of personal taste.
- I don't want to restrict the formats to only a few, you can personalize them in the system settings as described here #11
- "last item is cut at the bottom" - Could you provide a screenshot?
- "option not to reset the calendar" - That's against the idea of the calendar, which is to focus on your current day schedule. You can "lock" the selected date with the lock icon until you don't need it anymore.
- Hovering over a date to display the list of events seems unnecessary and it's another feature to maintain.

Every new option I add to the app has to be carefully considered because it involves creating unit tests, UI tests and translating to every supported language. I also want to keep the app as clean and minimalist as possible.

**Comment by decodism** [comment]
- Yes, it is subjective. They just seemed less "standard" to me.
- I meant adding those basic formats in addition to the system ones. The problem with the system ones is that you cannot add more and I guess you are not interested in reimplementing the system interface with token fields.
- Sure:
<img width="359" src="https://user-images.githubusercontent.com/77468771/166470605-c56746a2-3e10-45f3-a998-1cd85537ba8c.png"><img width="340" src="https://user-images.githubusercontent.com/77468771/166470634-e0e0ca50-1f43-4779-98e1-4449113fd7a3.png">
- Someone could argue that resetting is easy to access.
- It allows to quickly see the events over several days.

Of course, only implement the options you think are worthwhile. By the way, it would be nice if the app had an icon but I cannot help in that area.

**Comment by pakerwreah** [comment]
I'm a dark mode lover, didn't see that bug 😅
I will fix that and also consider adding the option to not reset the date.
Thanks for the suggestions 🙇🏻‍♂️
