### ISSUE TITLE
Make the main view less cluttered (shortcuts)

### ISSUE THREAD

**Issue by gferreroferri** [pakerwreah/Calendr#82]
Hi, is it necessary to have the calendar selection button in the main view? Isn't enough to have it in the settings? This is not something you change often and I think in the settings it should be enough. It would also make the main view less cluttered and avoid confusion between the Reminders icon and the calendar selection that looks like a task button

**Comment by pakerwreah** [comment]
I often disable some of my work calendars that have too much irrelevant information but sometimes I want to see who is on vacation and for how long, so that's a game changer for me, but I do agree that the app has too many buttons in the main view.

I might have to add an option to show/hide these shortcuts. If I rarely create reminders, maybe it doesn't make sense to have that button there all the time.

Perhaps it would make more sense to have them in a context menu in the "settings" button, that way we don't need icons at all and they would be self-explanatory.

About the icon though, It's hard to find an icon that represents a "calendar picker" but differs from "open calendar" 🤷🏻‍♂️ ... I think the checkmark is a good fit and when the user clicks it once, it knows what it does.

I will explore some solutions but I can't promise anything (I'm a lazy person).
