### ISSUE TITLE
Design propositions

### ISSUE THREAD

**Issue by ismslv** [pakerwreah/Calendr#99]
1. Consider removing or adding the possibility to hide the "arrow" on the top of the popup. It looks a little outdated (matches more the style of "cat" era MacOSes). In all other aspects it looks very native and clean.

<img src="https://i.ibb.co/wKhWWg0/Screenshot-2022-12-14-at-02-18-19.png" width="400px"/>

2. Consider adding a possibility to style an icon, at least adding a background, like itsycal does it on the right.

3. Some people may have other weekend days than saturday and sunday (I'm speaking about these two columns being highlighted).

PS Your small personal app right now is the best small menubar calendar (with reminders!). Thank you.

**Comment by pakerwreah** [comment]
1. The arrow is built in to the native macOS popovers, to remove it I would have to rewrite a good part of the app using some other component, so it's not in my plans right now.

2. I will see if it isn't too complex to implement, because I personally don't think it brings that much value.

3. That's another feature I don't think brings much value, since I don't have a huge user base, but that's a bit easier to do (I think).

Thanks for your suggestions, I will definitely check them all when I have some time. 🙂
That said, I'm a lazy person and basically I built the app for myself, so I tend to be selective with feature requests, unless I like the idea or it becomes necessary (like the date format, after macOS 13 removed the configuration from the system).
